'use client';

import { AIAnalysis } from '@/types';
import { Brain, AlertCircle, Lightbulb, BarChart2, CheckCircle } from 'lucide-react';
import { SeverityBadge, PriorityBadge } from './Badges';
import { formatDate } from '@/lib/constants';

interface AIAnalysisCardProps {
  analysis: AIAnalysis;
  showDisclaimer?: boolean;
}

export default function AIAnalysisCard({ analysis, showDisclaimer = true }: AIAnalysisCardProps) {
  const isMock = analysis.model_name === 'mock-v1';
  const isOllama = analysis.model_name !== 'mock-v1' && !analysis.model_name.startsWith('gemini');
  const confidencePct = Math.round(analysis.confidence * 100);
  const confidenceColor =
    analysis.confidence >= 0.8 ? 'text-green-400' :
    analysis.confidence >= 0.6 ? 'text-yellow-400' : 'text-orange-400';

  return (
    <div className="bg-gray-900 border border-cyan-500/20 rounded-2xl overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-cyan-500/10 to-blue-500/10 border-b border-cyan-500/20 px-5 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-cyan-500/20 flex items-center justify-center">
            <Brain className="w-5 h-5 text-cyan-400" />
          </div>
          <div>
            <p className="font-semibold text-white text-sm">AI Analysis</p>
            <p className="text-xs text-cyan-400">
              {isMock
                ? '⚠️ Development Mock (mock-v1)'
                : isOllama
                ? `🦙 Ollama · ${analysis.model_name}`
                : `Model: ${analysis.model_name}`}
            </p>
          </div>
        </div>
        <div className="text-right">
          <p className={`text-xl font-bold ${confidenceColor}`}>{confidencePct}%</p>
          <p className="text-xs text-gray-400">confidence</p>
        </div>
      </div>

      {/* Mock disclaimer */}
      {isMock && showDisclaimer && (
        <div className="mx-5 mt-4 px-3 py-2 bg-amber-500/10 border border-amber-500/20 rounded-lg flex items-start gap-2">
          <AlertCircle className="w-4 h-4 text-amber-400 flex-shrink-0 mt-0.5" />
          <p className="text-xs text-amber-300">
            This analysis was generated by the <strong>development mock AI</strong> (mock-v1), not a real model.
            Set <code className="bg-amber-500/20 px-1 rounded">AI_PROVIDER=ollama</code> in <code className="bg-amber-500/20 px-1 rounded">.env</code> to enable real local AI analysis.
          </p>
        </div>
      )}

      {/* Ollama badge */}
      {isOllama && showDisclaimer && (
        <div className="mx-5 mt-4 px-3 py-2 bg-emerald-500/10 border border-emerald-500/20 rounded-lg flex items-start gap-2">
          <CheckCircle className="w-4 h-4 text-emerald-400 flex-shrink-0 mt-0.5" />
          <p className="text-xs text-emerald-300">
            Powered by <strong>local Ollama AI</strong> — <span className="font-mono">{analysis.model_name}</span>. Analysis runs entirely on your machine, no data sent to external servers.
          </p>
        </div>
      )}

      {/* Body */}
      <div className="p-5 space-y-4">
        {/* Category + Severity + Priority row */}
        <div className="flex flex-wrap gap-3 items-center">
          <span className="text-xs text-gray-400 bg-gray-800 px-3 py-1 rounded-full">
            {analysis.detected_category}
          </span>
          <SeverityBadge severity={analysis.severity as any} />
          <PriorityBadge priority={
            analysis.severity === 'CRITICAL' ? 'P1' :
            analysis.severity === 'HIGH' ? 'P2' :
            analysis.severity === 'MEDIUM' ? 'P3' : 'P4'
          } />
        </div>

        {/* Confidence Bar */}
        <div>
          <div className="flex justify-between text-xs text-gray-400 mb-1.5">
            <span>Confidence Score</span>
            <span className={confidenceColor}>{confidencePct}%</span>
          </div>
          <div className="h-2 bg-gray-800 rounded-full overflow-hidden">
            <div
              className={`h-full rounded-full transition-all duration-700 ${
                analysis.confidence >= 0.8 ? 'bg-green-500' :
                analysis.confidence >= 0.6 ? 'bg-yellow-500' : 'bg-orange-500'
              }`}
              style={{ width: `${confidencePct}%` }}
            />
          </div>
        </div>

        {/* Explanation */}
        <div className="bg-gray-800/50 rounded-xl p-4">
          <p className="text-xs text-gray-400 font-medium mb-1.5 flex items-center gap-1">
            <BarChart2 className="w-3.5 h-3.5" /> Analysis
          </p>
          <p className="text-sm text-gray-300 leading-relaxed">{analysis.explanation}</p>
        </div>

        {/* Recommended Action */}
        <div className="bg-emerald-500/5 border border-emerald-500/20 rounded-xl p-4">
          <p className="text-xs text-emerald-400 font-medium mb-1.5 flex items-center gap-1">
            <Lightbulb className="w-3.5 h-3.5" /> Recommended Action
          </p>
          <p className="text-sm text-gray-300 leading-relaxed">{analysis.recommended_action}</p>
        </div>

        <p className="text-xs text-gray-600 text-right">
          Analyzed {formatDate(analysis.created_at)}
        </p>
      </div>
    </div>
  );
}
